### PR TITLE
delete multiple records

### LINKED ISSUE #40: `kbsecret rm` should be able to delete multiple records at once
Currently, `kbsecret rm` only deletes one record at a time:

```bash
$ kbsecret rm foo        # this works
$ kbsecret rm foo bar    # this fails
Fatal: Too many arguments given (2, expected 1).
```

For consistency with `kbsecret login` and `kbsecret env`, `kbsecret rm` should be able to delete multiple records at once.

Passing a nonexistent record to `kbsecret rm` should fail the command before **any** records are deleted, just as it does now.

### PR DESCRIPTION
**Pull request by nmonti**
Fixes #40

- [x] Have you run `make test` locally and ensured that all tests pass?
- [x] Have you run `make coverage` locally and ensured that coverage did not drop?

*If* you're changing something in the library:
- [ ] Have you introduced unit tests for your changes?

*If* you're changing something in the CLI:
- [x] Have you updated the manual pages and shell completion (if necessary)?
- [x] Have you introduced CLI unit tests for your changes and ensured that `make test-cli` passes?

Added the ability to delete multiple records at once. The test coverage went from `628 / 656 LOC (95.73%)` to `645 / 676 LOC (95.41%)` if that's alright (I don't see anything else to test for this unless I'm missing something).

### CODE REVIEW

File: lib/kbsecret/session.rb [hunk 1]
```diff
@@ -92,6 +92,27 @@ def delete_record(label)
       records.delete(record)
     end
 
+    # Delete an array of records from the session, if they exist. Does nothing
+    # if no such record can be found.
+    # @param labels [Array<[String, :Symbol]>] the labels of the records to delete
+    # @return [void]
+    def delete_records(labels)
```
Comment (woodruffw) [inline lib/kbsecret/session.rb]: This feature shouldn't require any new API surface -- all the changes should happen in the CLI.

File: test/test_records.rb [hunk 2]
```diff
@@ -36,6 +36,23 @@ def test_record_types
     end
   end
 
+  def test_deletion_of_multiple_records
```
Comment (woodruffw) [inline test/test_records.rb]: Drop this test along with the changes to `KBSecret::Session`.

File: lib/kbsecret/cli/kbsecret-rm [hunk 3]
```diff
@@ -12,29 +12,33 @@ cmd = CLI.create do |c|
   c.slop do |o|
     o.banner = <<~HELP
       Usage:
-        kbsecret rm [options] <record>
+        kbsecret rm [options] <record [records ...]>
```
Comment (woodruffw) [inline lib/kbsecret/cli/kbsecret-rm]: Depluralize `records`, for consistency with `kbsecret env` and `kbsecret login`:

```
kbsecret rm [options] <record [record ...]>
```

File: lib/kbsecret/cli/kbsecret-rm [hunk 4]
```diff
@@ -12,29 +12,33 @@ cmd = CLI.create do |c|
...
 
-label = cmd.args[:label]
+records = cmd.session.records :login
 
-cmd.die "Can't delete a nonexistent record." unless cmd.session.record? label
+selected_records = records.select do |record|
+  cmd.args[:labels].include? record.label
+end
+
+cmd.die "Can't delete a nonexistent record." unless selected_records
```
Comment (woodruffw) [inline lib/kbsecret/cli/kbsecret-rm]: `selected_records` will always be an `Array`, so this condition will always fail.

It should probably be something like this:

```ruby
cmd.die "No such record(s)." if selected_records.empty?
```

File: lib/kbsecret/cli/kbsecret-rm [hunk 5]
```diff
@@ -12,29 +12,33 @@ cmd = CLI.create do |c|
...
 
 tty = TTY::Prompt.new
 
 confirm = if cmd.opts.interactive?
-            tty.yes?("Delete '#{label}' from the #{cmd.session.label} session?")
+            tty.yes?("Delete '#{selected_records.join(",")}' from the #{cmd.session.label} session?")
```
Comment (woodruffw) [inline lib/kbsecret/cli/kbsecret-rm]: Join with spaces: `join(", ")`

File: lib/kbsecret/cli/kbsecret-rm [hunk 6]
```diff
@@ -12,29 +12,33 @@ cmd = CLI.create do |c|
...
           else true
           end
 
-cmd.session.delete_record(label) if confirm
+cmd.session.delete_records(selected_records) if confirm
```
Comment (woodruffw) [inline lib/kbsecret/cli/kbsecret-rm]:
```ruby
selected_records.each { |r| cmd.session.delete_record(r.label) } if confirm
```

**Comment by woodruffw** [comment]
Thanks for tackling this! I've left some review notes above.

**Comment by nmonti** [comment]
Thanks for the feedback! I implemented your suggestions, but I'm now getting 4 failing tests:

```
CLINewTest#test_todo = 1.65 s = E
CLINewTest#test_unstructured = 1.64 s = E
CLINewTest#test_environment = 1.42 s = E
CLINewTest#test_snippet = 1.42 s = E
```
Each failing at this line:
```ruby
# remove unstructured:
run_command_and_stop "kbsecret rm #{label}"
```
I'm not sure why since other passing tests call `rm` and the code appears pretty straightforward. I'll commit the changes in a second

File: lib/kbsecret/cli/kbsecret-rm [hunk 7]
```diff
@@ -12,29 +12,33 @@ cmd = CLI.create do |c|
...
   c.dreck do
-    string :label
+    list :string, :labels
   end
 
   c.ensure_session!
 end
 
-label = cmd.args[:label]
+records = cmd.session.records :login
```
Comment (woodruffw) [inline lib/kbsecret/cli/kbsecret-rm]: Drop the `:login` here - we want *all* records, not just `login` typed ones. I think this is causing your test failures.

File: man/man1/kbsecret-rm.1.ronnpp [hunk 8]
```diff
@@ -3,24 +3,24 @@ kbsecret-rm(1) - remove a kbsecret(1) record
...
+	The session that the record(s) are under.
 
 * `-i`, `--interactive`:
 	Confirm deletion interactively.
 
 ## EXAMPLES
 
 ```
-	$ kbsecret rm gmail
+	$ kbsecret rm gmail youtube
```
Comment (woodruffw) [inline man/man1/kbsecret-rm.1.ronnpp]: Instead of changing the example, add a second example so that people understand that they can pass either one or many records to `kbsecret rm`.

**Comment by woodruffw** [comment]
Ping @nmonti re: changes above.

**Comment by nmonti** [comment]
Sorry I will get on that tonight (EST)!

**Comment by woodruffw** [comment]
> Sorry I will get on that tonight (EST)!

Not a problem, take your time. I just wanted to make sure this PR wasn't abandoned :smile:

**Comment by nmonti** [comment]
`The command "bash test/ci/setup.sh" failed and exited with 1 during .`

Any idea what is causing this? My tests all pass locally now (thanks!)

**Comment by woodruffw** [comment]
> Any idea what is causing this? My tests all pass locally now (thanks!)

Yep, it's on my end (you can ignore it). It has to do with the fact that Travis CI doesn't let forks use secret environment variables, and the unit tests rely on one.

**Comment by woodruffw** [comment]
This PR is looking good to me. I'm going to do some local testing, and hopefully have it merged in a bit!

**Comment by nmonti** [comment]
Awesome! Sorry for the delay, had a busy week
